#ifndef SCREEN_CONFIG_H
#define SCREEN_CONFIG_H

#include "LPN_config.h"

#if LPN == LPN_ID_2
#define EPAPER_MODULE2_9 0
#else
#define EPAPER_MODULE2_9 1
#endif 

#if EPAPER_MODULE2_9
#define EPAPER_MODULE1_54 0
#else 
#define EPAPER_MODULE1_54 1
#endif

#if EPAPER_MODULE2_9
#define PAPER_PIXEL_WIDTH  128
#define PAPER_PIXEL_HEIGHT 296
#else
#define PAPER_PIXEL_WIDTH  200
#define PAPER_PIXEL_HEIGHT 200
#endif

#define WSEPD_HEIGHT PAPER_PIXEL_HEIGHT
#define WSEPD_WIDTH PAPER_PIXEL_WIDTH

#define PAPER_RST_PIN 28
#define PAPER_DC_PIN  30
#define PAPER_VCC_PIN 5

#define PAPER_SPI_INSTANCE 1
#define PAPER_SPI_SS_PIN   29
#define PAPER_SPI_MOSI_PIN 4
#define PAPER_SPI_SCK_PIN  3

#define WSEPD_DC PAPER_DC_PIN
#define WSEPD_RST PAPER_RST_PIN
#define WSEPD_VCC PAPER_VCC_PIN
#define WSEPD_BUSY 31

#define WSEPD_SPI_INSTANCE PAPER_SPI_INSTANCE
#define WSEPD_SPI_CS PAPER_SPI_SS_PIN
#define WSEPD_SPI_MOSI PAPER_SPI_MOSI_PIN
#define WSEPD_SPI_CLK PAPER_SPI_SCK_PIN

#endif